name: submodule

on:
  push:
    branches:
      - 'main'

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ashurmatovlochinbek/git-submodule/dispatches \
            -d '{"event_type":"catching-notify-update"}'
